### ISSUE TITLE
Not installable on latest version of VS2019

### ISSUE THREAD

**Issue by human-0** [HJLebbink/intrinsics-dude#7]
This extension is not shown when installing from visual studio's extension manager. If you try to install it by downloading it from the marketplace, there is the error "This extension is not installable on any currently installed products".

**Comment by ivan-achlaqullah** [comment]
I got same error when installing on vs2019.

```
20/08/2019 04.18.10 - Microsoft VSIX Installer
20/08/2019 04.18.10 - -------------------------------------------
20/08/2019 04.18.10 - vsixinstaller.exe version:
20/08/2019 04.18.10 - 16.2.3073
20/08/2019 04.18.10 - -------------------------------------------
20/08/2019 04.18.10 - Command line parameters:
20/08/2019 04.18.10 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Username\Downloads\IntrinsicsDude.vsix
20/08/2019 04.18.10 - -------------------------------------------
20/08/2019 04.18.10 - Microsoft VSIX Installer
20/08/2019 04.18.10 - -------------------------------------------
20/08/2019 04.18.11 - Initializing Install...
20/08/2019 04.18.11 - Extension Details...
20/08/2019 04.18.11 - 	Identifier         : 5BC76C2B-A941-40D2-9EB4-F0DB92DD7C06
20/08/2019 04.18.11 - 	Name               : Intrinsics Dude
20/08/2019 04.18.11 - 	Author             : Henk-Jan Lebbink
20/08/2019 04.18.11 - 	Version            : 1.2.0.1
20/08/2019 04.18.11 - 	Description        : Improved Statement Completion, Quickinfo Tooltips and Signature Help for Compiler Intrinsics in Visual Studio
20/08/2019 04.18.11 - 	Locale             : en-US
20/08/2019 04.18.11 - 	MoreInfoURL        : https://github.com/HJLebbink/intrinsics-dude
20/08/2019 04.18.11 - 	InstalledByMSI     : False
20/08/2019 04.18.11 - 	SupportedFrameworkVersionRange : [4.7.2,)
20/08/2019 04.18.11 - 
20/08/2019 04.18.11 - 	SignatureState     : Unsigned
20/08/2019 04.18.11 - 	Supported Products : 
20/08/2019 04.18.11 - 		Microsoft.VisualStudio.Pro
20/08/2019 04.18.11 - 			Version : [14.0,16.0]
20/08/2019 04.18.11 - 		Microsoft.VisualStudio.Community
20/08/2019 04.18.11 - 			Version : [14.0,16.0]
20/08/2019 04.18.11 - 		Microsoft.VisualStudio.Enterprise
20/08/2019 04.18.11 - 			Version : [14.0,16.0]
20/08/2019 04.18.11 - 
20/08/2019 04.18.11 - 	References         : 
20/08/2019 04.18.11 - 	Prerequisites      : 
20/08/2019 04.18.11 - 		-------------------------------------------------------
20/08/2019 04.18.11 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
20/08/2019 04.18.11 - 		Name         : Visual Studio core editor
20/08/2019 04.18.11 - 		Version      : [15.8.27729.1,16.0]
20/08/2019 04.18.11 - 
20/08/2019 04.18.11 - 		-------------------------------------------------------
20/08/2019 04.18.11 - 		Identifier   : Microsoft.Net.Component.4.7.2.SDK
20/08/2019 04.18.11 - 		Name         : .NET Framework 4.7.2 SDK
20/08/2019 04.18.11 - 		Version      : [15.6.27406.0,16.0]
20/08/2019 04.18.11 - 
20/08/2019 04.18.11 - Signature Details...
20/08/2019 04.18.11 - 	Extension is not signed.
20/08/2019 04.18.11 - 
20/08/2019 04.18.11 - Searching for applicable products...
20/08/2019 04.18.11 - Found installed product - Global Location
20/08/2019 04.18.11 - Found installed product - Visual Studio Community 2019
20/08/2019 04.18.11 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by HJLebbink** [comment]
Thanx for pointing this out. Version 1.2.1.0 should have this fixed.
